# Generated by Django 3.2.4 on 2021-07-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BirthDay', '0002_amna_zafer_transparant_imag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amna_Zafer',
            new_name='EmanAlbum',
        ),
    ]
